### ISSUE TITLE
Improve `deploy.yml` workflow

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#164]
The [`deploy.yml`](https://github.com/JokeNetwork/vegancheck.me/blob/main/.github/workflows/deploy.yml) workflows fails too often. 
That is because when building the app, the server sometimes runs out of memory. 

Retrying the workflow often solves the issue. We need a way to run the workflow again if it fails.
A maximum retry cap should be set to 3. 

We could try it like this:
````yaml
name: "Retry action using retry step"
on:
	# This action is called when this is pushed to GitHub
	push:
	# This action can be manually triggered
	workflow_call:
jobs:
    # This name is up to you
	retry-job:
		runs-on: "ubuntu-latest"
		name: My Job
		steps:
			- name: Checkout repository
			  uses: actions/checkout@v3

			- name: Some action that can fail
			  # You need to specify an id to be able to tell what the status of this action was
			  id: myStepId1
			  # This needs to be true to proceed to the next step of failure
			  continue-on-error: true
			  uses: actions/someaction

			# Duplicate of the step that might fail ~ manual retry
			- name: Some action that can fail
			  id: myStepId2
			  # Only run this step if step 1 fails. It knows that step one failed because we specified an `id` for the first step
			  if: steps.myStepId1.outcome == 'failure'
			  # This needs to be true to proceed to the next step of failure
			  continue-on-error: true
			  uses: actions/someaction
````

(Sourced from https://www.thisdot.co/blog/how-to-retry-failed-steps-in-github-action-workflows)
