### ISSUE TITLE
[Possible feature] Add border to `#results`-div

### ISSUE THREAD

**Issue by philipbrembeck** [frontendnetwork/veganify#67]
<img width="651" alt="Bildschirmfoto 2021-12-23 um 19 21 23" src="https://user-images.githubusercontent.com/4144601/147278910-9eb5d82f-532a-4223-b55d-11a18a3266b0.png">

``` css
#results {
  border: 0.063rem solid #424242;
  cursor: pointer;
  padding: 0.25rem 0.5rem;
  font-size: 0.875rem;
  border-radius: 0.5rem;
  padding: 2rem;
  margin-left: 1rem;
  margin-right: 1rem;
}
```
